apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
  template.app-sync-failed: |
    message: |
      :x: Application {{.app.metadata.name}} failed to sync.
      Cluster: {{.app.spec.destination.server}}
  template.app-sync-succeeded: |
    message: |
      :white_check_mark: Application {{.app.metadata.name}} synced successfully.
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase == 'Succeeded'
      send: [app-sync-succeeded]
