apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus-rules-cluster-health.yaml
  - prometheus-rules-platform.yaml
  - grafana-dashboard-configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: hybrid-k8s-platform
  app.kubernetes.io/component: monitoring
