#!/usr/bin/env bash
# gcp-deploy.sh — GCP login helper + full platform deploy (infra + Linkding app)
#
# Usage:
#   ./scripts/gcp-deploy.sh              # interactive: auth → init → infra → apps
#   ./scripts/gcp-deploy.sh auth           # browser login only
#   ./scripts/gcp-deploy.sh init           # create local config/terraform.tfvars
#   ./scripts/gcp-deploy.sh infra          # phase 1 + phase 2 (GCE + GCS)
#   ./scripts/gcp-deploy.sh apps           # Argo CD root app + ApplicationSets
#   ./scripts/gcp-deploy.sh all            # everything
#
# Optional env vars (skip prompts):
#   GCP_PROJECT=hybrid-k8s-dev
#   ADMIN_CIDR=203.0.113.10/32
#   SSH_PUBLIC_KEY="ssh-ed25519 AAAA..."
#   SKIP_AUTH=1
#   SKIP_APPS=1
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/inventory-utils.sh
source "${SCRIPT_DIR}/inventory-utils.sh"
PRIMARY_TFVARS="${REPO_ROOT}/primary-cluster-gcp/terraform.tfvars"
STANDBY_TFVARS="${REPO_ROOT}/cloud-services-gcp/terraform.tfvars"
CONFIG="${REPO_ROOT}/config/clusters.yaml"
KUBECONFIG_PATH="${KUBECONFIG_PATH:-${HOME}/.kube/hybrid-primary.yaml}"

log() { echo "==> $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "'$1' not found. Install it and retry."
}

require_prereqs() {
  require_cmd gcloud
  require_cmd terraform
  require_cmd ansible-playbook
  require_cmd jq
  require_cmd curl
  require_cmd kubectl
}

detect_ssh_public_key() {
  if [[ -n "${SSH_PUBLIC_KEY:-}" ]]; then
    return
  fi
  for key in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    if [[ -f "$key" ]]; then
      SSH_PUBLIC_KEY="$(cat "$key")"
      return
    fi
  done
  die "No SSH public key found. Set SSH_PUBLIC_KEY or create ~/.ssh/id_ed25519.pub"
}

detect_admin_cidr() {
  if [[ -n "${ADMIN_CIDR:-}" ]]; then
    return
  fi
  local ip
  ip="$(curl -fsS --max-time 10 ifconfig.me 2>/dev/null || curl -fsS --max-time 10 icanhazip.com 2>/dev/null || true)"
  [[ -n "$ip" ]] || die "Could not detect public IP. Set ADMIN_CIDR=YOUR.IP/32"
  ADMIN_CIDR="${ip}/32"
  log "Detected admin CIDR: ${ADMIN_CIDR}"
}

resolve_gcp_project() {
  if [[ -n "${GCP_PROJECT:-}" ]]; then
    return
  fi
  GCP_PROJECT="$(gcloud config get-value project 2>/dev/null || true)"
  if [[ -z "$GCP_PROJECT" || "$GCP_PROJECT" == "(unset)" ]]; then
    read -r -p "GCP project ID: " GCP_PROJECT
  else
    read -r -p "GCP project ID [${GCP_PROJECT}]: " REPLY
    GCP_PROJECT="${REPLY:-$GCP_PROJECT}"
  fi
  [[ -n "$GCP_PROJECT" ]] || die "GCP project ID is required"
}

check_gcp_auth() {
  if gcloud auth application-default print-access-token >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

cmd_auth() {
  "${REPO_ROOT}/scripts/gcp-auth.sh"
}

update_tfvars_project() {
  local path="$1"
  [[ -f "$path" ]] || return
  if grep -q '^gcp_project' "$path"; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
      sed -i '' "s/^gcp_project[[:space:]]*=.*/gcp_project    = \"${GCP_PROJECT}\"/" "$path"
    else
      sed -i "s/^gcp_project[[:space:]]*=.*/gcp_project    = \"${GCP_PROJECT}\"/" "$path"
    fi
    log "Updated gcp_project in ${path} → ${GCP_PROJECT}"
  fi
}

write_tfvars() {
  local path="$1"
  local dir
  dir="$(dirname "$path")"

  detect_ssh_public_key
  detect_admin_cidr
  resolve_gcp_project

  if [[ -f "$path" && "${FORCE_TFVARS:-}" != "1" ]]; then
    update_tfvars_project "$path"
    return
  fi

  cat > "$path" <<EOF
# Local only — gitignored. Generated by scripts/gcp-deploy.sh init

gcp_project    = "${GCP_PROJECT}"
gcp_region     = "us-central1"
gcp_zones      = ["us-central1-a", "us-central1-b"]

project_name   = "hybrid-k8s"

ssh_public_key = "${SSH_PUBLIC_KEY}"
admin_cidr     = "${ADMIN_CIDR}"
EOF

  if [[ "$dir" == *cloud-services-gcp* ]]; then
    cat >> "$path" <<EOF

standby_node_count   = 2
standby_machine_type = "e2-small"
EOF
  else
    cat >> "$path" <<EOF

control_plane_count        = 1
worker_count               = 2
control_plane_machine_type = "e2-medium"
worker_machine_type        = "e2-small"
EOF
  fi

  log "Created ${path}"
}

cmd_init() {
  require_cmd gcloud

  if [[ ! -f "$CONFIG" ]]; then
    cp "${REPO_ROOT}/config/clusters.example.yaml" "$CONFIG"
    log "Created ${CONFIG}"
  fi

  write_tfvars "$PRIMARY_TFVARS"
  write_tfvars "$STANDBY_TFVARS"

  resolve_gcp_project
  gcloud config set project "$GCP_PROJECT"

  log "Using GCP project: ${GCP_PROJECT}"
  log "Local config ready. Run: ./scripts/gcp-deploy.sh infra"
}

enable_gcp_apis() {
  resolve_gcp_project
  "${REPO_ROOT}/scripts/gcp-enable-apis.sh"
}

cmd_infra() {
  require_prereqs
  [[ -f "$PRIMARY_TFVARS" ]] || die "Run ./scripts/gcp-deploy.sh init first"
  [[ -f "$STANDBY_TFVARS" ]] || die "Run ./scripts/gcp-deploy.sh init first"

  check_gcp_auth || {
    log "GCP credentials not found — starting browser login"
    cmd_auth
  }

  enable_gcp_apis

  log "Phase 1 — primary cluster"
  "${REPO_ROOT}/scripts/phase1-primary.sh"

  log "Phase 2 — standby cluster + GCS backups"
  "${REPO_ROOT}/scripts/phase2-standby.sh"

  configure_velero_on_primary

  log "Infrastructure deploy complete"
}

configure_velero_on_primary() {
  "${REPO_ROOT}/scripts/configure-velero-primary.sh"
}

cmd_failover() {
  require_prereqs
  check_gcp_auth || {
    log "GCP credentials not found — starting browser login"
    cmd_auth
  }
  enable_gcp_apis

  local shared_tfvars="${REPO_ROOT}/shared-services-gcp/terraform.tfvars"
  [[ -f "$shared_tfvars" ]] || die "Missing ${shared_tfvars} — copy from terraform.tfvars.example (see docs/PHASE-4-RUNBOOK.md)"

  log "Phase 4 — shared-services-gcp (witness + optional Cloud DNS)"
  (
    cd "${REPO_ROOT}/shared-services-gcp"
    terraform init -input=false
    terraform apply -auto-approve -input=false
  )

  log "Phase 4 apply complete — see docs/PHASE-4-RUNBOOK.md for NS, witness verify, and ./scripts/failover-gcp.sh"
}

setup_kubeconfig() {
  local inventory="${REPO_ROOT}/ansible/inventory/primary-hosts.yml"
  [[ -f "$inventory" ]] || die "Missing ${inventory} — run infra first"

  local cp_ip
  cp_ip="$(inventory_first_control_plane_ip "$inventory")"
  [[ -n "$cp_ip" ]] || die "Could not read control plane IP from inventory"

  mkdir -p "$(dirname "$KUBECONFIG_PATH")"
  ssh -o StrictHostKeyChecking=no "ubuntu@${cp_ip}" "sudo cat /etc/rancher/k3s/k3s.yaml" > "$KUBECONFIG_PATH"
  sed -i "s/127.0.0.1/${cp_ip}/" "$KUBECONFIG_PATH"
  chmod 600 "$KUBECONFIG_PATH"

  export KUBECONFIG="$KUBECONFIG_PATH"
  log "Kubeconfig: ${KUBECONFIG_PATH}"
}

wait_for_argocd() {
  export KUBECONFIG="$KUBECONFIG_PATH"
  log "Waiting for Argo CD server..."
  for _ in $(seq 1 60); do
    if kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server --field-selector=status.phase=Running 2>/dev/null | grep -q Running; then
      return 0
    fi
    sleep 10
  done
  die "Argo CD did not become ready in time"
}

cmd_apps() {
  require_prereqs
  setup_kubeconfig
  wait_for_argocd

  export KUBECONFIG="$KUBECONFIG_PATH"

  log "Deploying Argo CD ApplicationSets + root app"
  kubectl apply -f "${REPO_ROOT}/gitops/argocd/applicationsets/"
  kubectl apply -f "${REPO_ROOT}/gitops/argocd/applications/root-app.yaml"
  kubectl apply -f "${REPO_ROOT}/gitops/argocd/applications/infra-monitoring.yaml" || true

  log "Waiting for Linkding deployment..."
  kubectl wait --for=condition=available deployment/linkding -n linkding --timeout=300s 2>/dev/null || {
    log "Linkding not ready yet — check: kubectl get applications -n argocd"
  }

  local cp_ip lb_ip
  cp_ip="$(inventory_first_control_plane_ip "${REPO_ROOT}/ansible/inventory/primary-hosts.yml")"
  lb_ip="$(terraform -chdir="${REPO_ROOT}/primary-cluster-gcp" output -raw primary_lb_ip 2>/dev/null || true)"

  echo ""
  echo "========================================"
  echo " Apps deployed via Argo CD"
  echo "========================================"
  echo "Kubeconfig:  export KUBECONFIG=${KUBECONFIG_PATH}"
  echo "Argo CD UI:  kubectl port-forward svc/argocd-server -n argocd 8080:443"
  echo "             (admin password: changeme — from Ansible values)"
  echo ""
  echo "Linkding:"
  if [[ -n "$lb_ip" ]]; then
    echo "  https://${lb_ip}  (via Traefik NodePort/LB — may need Host header or ingress host)"
  fi
  echo "  Quick test: kubectl port-forward svc/linkding -n linkding 9090:9090"
  echo "              → http://localhost:9090"
  echo ""
  echo "Nodes:       kubectl get nodes"
  echo "Apps:        kubectl get applications -n argocd"
  echo "========================================"
}

cmd_all() {
  require_prereqs

  if [[ "${SKIP_AUTH:-}" != "1" ]]; then
    check_gcp_auth || cmd_auth
  fi

  cmd_init
  cmd_infra

  if [[ "${SKIP_APPS:-}" != "1" ]]; then
    cmd_apps
  fi
}

usage() {
  cat <<EOF
Usage: $(basename "$0") [command]

Commands:
  auth      Sign in to GCP via browser (no secrets in git)
  init      Create local terraform.tfvars + clusters.yaml (gitignored)
  infra     Deploy primary + standby clusters (Terraform + Ansible)
  apps      Deploy Linkding and other apps via Argo CD
  failover  Apply shared-services-gcp (Phase 4 witness + optional DNS)
  all       auth + init + infra + apps (default; does not include failover)

Examples:
  ./scripts/gcp-deploy.sh
  GCP_PROJECT=hybrid-k8s-dev ./scripts/gcp-deploy.sh init
  ./scripts/gcp-deploy.sh infra
  ./scripts/gcp-deploy.sh failover
  SKIP_AUTH=1 ./scripts/gcp-deploy.sh all

See docs/GCP-DEPLOY.md and docs/PHASE-4-RUNBOOK.md.
EOF
}

main() {
  local cmd="${1:-all}"
  shift || true

  case "$cmd" in
    auth)  cmd_auth ;;
    init)  cmd_init ;;
    infra) cmd_infra ;;
    apps)  cmd_apps ;;
    failover|phase4) cmd_failover ;;
    all)   cmd_all ;;
    -h|--help|help) usage ;;
    *) die "Unknown command: ${cmd}. Run with --help" ;;
  esac
}

main "$@"
