#!/usr/bin/env bash
# generate-wg-client-config.sh — Write a stock WireGuard client profile
#
# Usage:
#   ./scripts/generate-wg-client-config.sh <city> [client-name]
#
# Expects vpn-clients/<city>/ to contain:
#   server.publickey, client.privatekey, client.publickey
# And endpoint IP via VPN_ENDPOINT or terraform output.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CITY="${1:?Usage: generate-wg-client-config.sh <city> [client-name]}"
CLIENT_NAME="${2:-laptop}"
DIR="${REPO_ROOT}/vpn-clients/${CITY}"
PORT="${WIREGUARD_PORT:-51820}"

need() { [[ -f "$1" ]] || { echo "ERROR: missing $1 — run vpn-bootstrap.sh first" >&2; exit 1; }; }

need "${DIR}/server.publickey"
need "${DIR}/client.privatekey"

if [[ -n "${VPN_ENDPOINT:-}" ]]; then
  ENDPOINT="$VPN_ENDPOINT"
elif [[ -d "${REPO_ROOT}/vpn-gateways-gcp" ]] && [[ -f "${REPO_ROOT}/vpn-gateways-gcp/terraform.tfstate" || -d "${REPO_ROOT}/vpn-gateways-gcp/terraform.tfstate.d" ]]; then
  ENDPOINT="$(terraform -chdir="${REPO_ROOT}/vpn-gateways-gcp" output -raw vpn_public_ip 2>/dev/null || true)"
fi

[[ -n "${ENDPOINT:-}" ]] || {
  echo "ERROR: Set VPN_ENDPOINT=<public-ip> or apply vpn-gateways-gcp first" >&2
  exit 1
}

FULL_TUNNEL="${WG_FULL_TUNNEL:-1}"
if [[ "$FULL_TUNNEL" == "1" ]]; then
  ALLOWED="0.0.0.0/0, ::/0"
else
  ALLOWED="${WG_ALLOWED_IPS:-10.66.0.0/24}"
fi

OUT="${DIR}/${CLIENT_NAME}-${CITY}.conf"
umask 077
cat >"$OUT" <<EOF
# fantastic-spoon WireGuard — city=${CITY} client=${CLIENT_NAME}
# Generated by scripts/generate-wg-client-config.sh
# Import into the official WireGuard app (macOS/iOS/Android/Linux).

[Interface]
PrivateKey = $(cat "${DIR}/client.privatekey")
Address = ${WG_CLIENT_ADDRESS:-10.66.0.2/32}
DNS = ${WG_DNS:-1.1.1.1}

[Peer]
PublicKey = $(cat "${DIR}/server.publickey")
Endpoint = ${ENDPOINT}:${PORT}
AllowedIPs = ${ALLOWED}
PersistentKeepalive = 25
EOF

echo "Wrote ${OUT}"
echo "Endpoint ${ENDPOINT}:${PORT}  AllowedIPs=${ALLOWED}"
