#!/usr/bin/env bash
# generate-wg-client-config.sh — Write a stock WireGuard client profile
#
# Usage:
#   ./scripts/generate-wg-client-config.sh <city> [client-name]
#
# Prefers vpn-clients/<city>/peers/<name>.* (multi-peer).
# Falls back to legacy client.privatekey for name=laptop.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export REPO_ROOT
# shellcheck source=vpn-peers-lib.sh
# shellcheck disable=SC1091
source "$(dirname "$0")/vpn-peers-lib.sh"

CITY="${1:?Usage: generate-wg-client-config.sh <city> [client-name]}"
CLIENT_NAME="${2:-laptop}"
DIR="$(vpn_peers_city_dir "$CITY")"
PEERS="$(vpn_peers_dir "$CITY")"
PORT="${WIREGUARD_PORT:-$(vpn_peers_tf_port)}"

vpn_peers_migrate_legacy "$CITY"

PRIV=""
PUB_SERVER="${DIR}/server.publickey"
ADDR=""

if [[ -f "${PEERS}/${CLIENT_NAME}.privatekey" ]]; then
  PRIV="${PEERS}/${CLIENT_NAME}.privatekey"
  ADDR="$(cat "${PEERS}/${CLIENT_NAME}.address")"
elif [[ "$CLIENT_NAME" == "laptop" && -f "${DIR}/client.privatekey" ]]; then
  PRIV="${DIR}/client.privatekey"
  ADDR="${WG_CLIENT_ADDRESS:-10.66.0.2/32}"
else
  echo "ERROR: missing peer keys for '${CLIENT_NAME}'" >&2
  echo "  Add with: ./scripts/vpn-peer-add.sh ${CITY} ${CLIENT_NAME}" >&2
  exit 1
fi

[[ -f "$PUB_SERVER" ]] || {
  echo "ERROR: missing $PUB_SERVER — run vpn-bootstrap.sh first" >&2
  exit 1
}

ENDPOINT="${VPN_ENDPOINT:-$(vpn_peers_tf_endpoint)}"
[[ -n "${ENDPOINT:-}" ]] || {
  echo "ERROR: Set VPN_ENDPOINT=<public-ip> or apply vpn-gateways-gcp first" >&2
  exit 1
}

FULL_TUNNEL="${WG_FULL_TUNNEL:-1}"
if [[ "$FULL_TUNNEL" == "1" ]]; then
  ALLOWED="0.0.0.0/0, ::/0"
else
  ALLOWED="${WG_ALLOWED_IPS:-10.66.0.0/24}"
fi

OUT="${DIR}/${CLIENT_NAME}-${CITY}.conf"
umask 077
cat >"$OUT" <<EOF
# fantastic-spoon WireGuard — city=${CITY} client=${CLIENT_NAME}
# Generated by scripts/generate-wg-client-config.sh
# Import into the official WireGuard app (macOS/iOS/Android/Linux).

[Interface]
PrivateKey = $(cat "$PRIV")
Address = ${ADDR}
DNS = ${WG_DNS:-1.1.1.1}

[Peer]
PublicKey = $(cat "$PUB_SERVER")
Endpoint = ${ENDPOINT}:${PORT}
AllowedIPs = ${ALLOWED}
PersistentKeepalive = 25
EOF

echo "Wrote ${OUT}"
echo "Endpoint ${ENDPOINT}:${PORT}  Address=${ADDR}  AllowedIPs=${ALLOWED}"
