#!/usr/bin/env bash
# vpn-prometheus-scrape-snippet.sh — Emit kube-prometheus-stack scrape config for the VPN gateway
#
# Usage:
#   ./scripts/vpn-prometheus-scrape-snippet.sh
#   ./scripts/vpn-prometheus-scrape-snippet.sh > /tmp/vpn-additional-scrape.yaml
#
# Then:
#   helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack \
#     -n monitoring -f /tmp/vpn-additional-scrape.yaml --reuse-values
#
# Firewall: set vpn_metrics_cidrs in vpn-gateways-gcp so Prometheus can reach :9100.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${REPO_ROOT}/vpn-gateways-gcp"

command -v terraform >/dev/null 2>&1 || {
  echo "ERROR: terraform not found" >&2
  exit 1
}

TARGET="$(terraform -chdir="$TF_DIR" output -raw vpn_metrics_url 2>/dev/null || true)"
CITY="$(terraform -chdir="$TF_DIR" output -raw vpn_city 2>/dev/null || echo us)"

[[ -n "$TARGET" ]] || {
  echo "ERROR: could not read vpn_metrics_url — apply vpn-gateways-gcp first" >&2
  exit 1
}

OUT="${VPN_SCRAPE_OUT:-}"
SNIPPET=$(cat <<EOF
# Generated by scripts/vpn-prometheus-scrape-snippet.sh — do not commit secrets/IPs if public
# Merge into kube-prometheus-stack (prometheus.prometheusSpec.additionalScrapeConfigs)
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: vpn-gateway
        scrape_interval: 30s
        metrics_path: /metrics
        static_configs:
          - targets:
              - "${TARGET}"
            labels:
              city: "${CITY}"
              role: vpn-gateway
              app: consumer-vpn
EOF
)

if [[ -n "$OUT" ]]; then
  printf '%s\n' "$SNIPPET" >"$OUT"
  echo "Wrote ${OUT}" >&2
else
  printf '%s\n' "$SNIPPET"
fi

cat <<EOF >&2

Next:
  1. Ensure vpn_metrics_cidrs includes the scraper IP (admin or primary NAT)
  2. helm upgrade ... -f <this-file> --reuse-values
  3. kubectl apply -k gitops/infrastructure/primary/monitoring/
  4. Grafana → Consumer VPN Gateway

See docs/MONITORING.md#consumer-vpn-gateway and docs/CONSUMER-VPN.md
EOF
